version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db  # Используем имя сервиса вместо IP
      DB_USER: user
      DB_PASS: root
      DB_NAME: hotel_db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'  # Разрешаем root доступ с любого хоста
    command: --default-authentication-plugin=mysql_native_password  # Важно для MySQL 8+
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8089:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local