version: '3.8'

services:
  # Сервис для веб-приложения (PHP + Apache)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  # Сервис для базы данных (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Сервис для phpMyAdmin для удобного управления базой данных
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8089:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

# Объявляем volume для хранения данных MySQL
volumes:
  mysql_data:
    driver: local
