
services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html/backend       # Бэкенд
      - ./backend/public:/var/www/html/public # Публичная папка
      - ./frontend/public:/var/www/html/frontend  # Если фронтенд нужен
    user: "1000:www-data"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db
    networks:
      - app-network
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql  # Используем именованный том
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  mysql_data:  # Объявляем именованный том

networks:
  app-network:
    driver: bridge